import { useEffect, useRef } from 'react';
import Vex from 'vexflow';

export interface SheetMusicProps {
  data: {
    clef?: string;
    keySignature?: string;
    timeSignature?: string;
    notes?: Array<{ keys: string[], duration: string }>;
  };
  width?: number;
  height?: number;
  className?: string;
  onRenderError?: (error: Error) => void;
}

/**
 * React component for rendering sheet music using VexFlow.
 * 
 * Converts music notation data (from Monsieur Engraver agent) into visual sheet music.
 * 
 * @example
 * ```tsx
 * <SheetMusic 
 *   data={{
 *     clef: 'treble',
 *     timeSignature: '4/4',
 *     keySignature: 'C',
 *     notes: [
 *       { keys: ['c/4'], duration: 'q' },
 *       { keys: ['d/4'], duration: 'q' }
 *     ]
 *   }}
 * />
 * ```
 */
export default function SheetMusic({ 
  data, 
  width = 450, 
  height = 150,
  className = '',
  onRenderError
}: SheetMusicProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    
    // Clear previous render
    container.innerHTML = '';
    
    try {
      const { Factory } = Vex.Flow;
      const vf = new Factory({
        renderer: { element: container, width, height }
      });

      const score = vf.EasyScore();
      const system = vf.System();

      const timeSig = data.timeSignature || '4/4';
      const clef = data.clef || 'treble';
      
      // Construct notes string for EasyScore
      // VexFlow EasyScore syntax: "C4/q, D4/q"
      let notesStr = '';
      if (data.notes && Array.isArray(data.notes)) {
        notesStr = data.notes.map(n => {
          // Normalize keys: "c/4" -> "c4" for VexFlow EasyScore
          const keys = n.keys.map(k => k.replace('/', '')).join(','); 
          return `${keys}/${n.duration}`;
        }).join(', ');
      }
      
      // Fallback if no notes
      if (!notesStr) notesStr = 'B4/w';

      system.addStave({
        voices: [
          score.voice(score.notes(notesStr, { stem: 'auto' }))
        ]
      })
      .addClef(clef)
      .addTimeSignature(timeSig);

      if (data.keySignature) {
        system.addKeySignature(data.keySignature);
      }

      vf.draw();
    } catch (e) {
      const error = e as Error;
      console.error("VexFlow Render Error:", error);
      
      if (onRenderError) {
        onRenderError(error);
      }
      
      container.innerHTML = `<div style="color: #ef4444; padding: 1rem;">Error rendering music: ${error.message}</div>`;
    }
  }, [data, width, height, onRenderError]);

  return (
    <div className={`sheet-music-container ${className}`}>
      <div ref={containerRef} className="vexflow-canvas"></div>
      <div style={{ fontSize: '0.75rem', color: '#9ca3af', textAlign: 'center', marginTop: '0.25rem' }}>
        Generated by Monsieur Engraver
      </div>
    </div>
  );
}
