import { app } from 'apprun';
import Vex from 'vexflow';

export interface SheetMusicProps {
  data: {
    clef?: string;
    keySignature?: string;
    timeSignature?: string;
    notes?: Array<{ keys: string[], duration: string }>;
  };
  width?: number;
  height?: number;
}

export default function SheetMusic({ data, width = 450, height = 150 }: SheetMusicProps) {
  const containerId = `vex-${Math.random().toString(36).substr(2, 9)}`;

  // Defer rendering until DOM is ready
  setTimeout(() => {
    const container = document.getElementById(containerId);
    if (!container) return;
    
    // Clear previous render
    container.innerHTML = '';
    
    try {
      const { Factory } = Vex.Flow;
      const vf = new Factory({
        renderer: { element: container, width, height }
      });

      const score = vf.EasyScore();
      const system = vf.System();

      const timeSig = data.timeSignature || '4/4';
      const clef = data.clef || 'treble';
      
      // Construct notes string for EasyScore
      // VexFlow EasyScore syntax: "C4/q, D4/q"
      let notesStr = '';
      if (data.notes && Array.isArray(data.notes)) {
        notesStr = data.notes.map(n => {
          // ensure keys are formatted like "c/4" -> "C4" if needed, 
          // but EasyScore usually likes "c4/q".
          // The prompt requested keys like "c/4".
          // VexFlow EasyScore expects "c4/w" or "c#4/h".
          // We might need to normalize "c/4" to "c4".
          const keys = n.keys.map(k => k.replace('/', '')).join(','); 
          return `${keys}/${n.duration}`;
        }).join(', ');
      }
      
      // Fallback if no notes
      if (!notesStr) notesStr = 'B4/w';

      system.addStave({
        voices: [
          score.voice(score.notes(notesStr, { stem: 'auto' }))
        ]
      })
      .addClef(clef)
      .addTimeSignature(timeSig);

      if (data.keySignature) {
          system.addKeySignature(data.keySignature);
      }

      vf.draw();
    } catch (e) {
      console.error("VexFlow Render Error:", e);
      container.innerHTML = `<div class="error">Error rendering music: ${(e as Error).message}</div>`;
    }
  }, 50);

  return (
    <div className="sheet-music-container p-4 bg-white rounded-lg shadow-sm my-2 overflow-x-auto">
      <div id={containerId} className="vexflow-canvas flex justify-center"></div>
      <div className="text-xs text-gray-400 text-center mt-1">Generated by Monsieur Engraver</div>
    </div>
  );
}
