/**
 * Demo Sheet Music Component
 *
 * Purpose:
 * - Render notation from structured tool payloads for the Infinite-Étude demo path.
 * - Keep music notation rendering isolated under demo components.
 *
 * Key Features:
 * - Draws stave/notes using VexFlow.
 * - Supports clef, key signature, time signature, and note arrays.
 * - Handles malformed/overfull measures with safe normalization.
 *
 * Notes on Implementation:
 * - Uses AppRun JSX and VexFlow factory rendering into a generated container node.
 * - This component is demo-only and is not part of production-default UX paths.
 *
 * Recent Changes:
 * - 2026-02-21: Restored location under `components/demos` after branch-level structure discussion.
 */

import { app } from 'apprun';
import { Factory, Voice } from 'vexflow';
import type { SheetMusicData } from '../../types';

function parseTimeSignature(timeSignature?: string): { numerator: number; denominator: number } {
  const match = /^\s*(\d+)\s*\/\s*(\d+)\s*$/.exec(String(timeSignature || '4/4'));
  if (!match) {
    return { numerator: 4, denominator: 4 };
  }

  const numerator = Number(match[1]);
  const denominator = Number(match[2]);

  if (!Number.isFinite(numerator) || numerator <= 0 || !Number.isFinite(denominator) || denominator <= 0) {
    return { numerator: 4, denominator: 4 };
  }

  return { numerator, denominator };
}

function durationToQuarterBeats(duration: string): number {
  switch (String(duration || '').trim()) {
    case 'w':
      return 4;
    case 'h':
      return 2;
    case 'q':
      return 1;
    case '8':
      return 0.5;
    case '16':
      return 0.25;
    default:
      return 1;
  }
}

function normalizeTimeSignatureForNotes(
  requestedTimeSig: string,
  notes: Array<{ keys: string[]; duration: string }>
): string {
  const { numerator, denominator } = parseTimeSignature(requestedTimeSig);
  const requestedCapacityInQuarters = numerator * (4 / denominator);
  const totalInQuarters = notes.reduce((sum, note) => sum + durationToQuarterBeats(note.duration), 0);

  if (totalInQuarters <= requestedCapacityInQuarters) {
    return `${numerator}/${denominator}`;
  }

  const expandedNumerator = Math.max(1, Math.ceil(totalInQuarters / (4 / denominator)));
  return `${expandedNumerator}/${denominator}`;
}

export interface SheetMusicProps {
  data: SheetMusicData;
  width?: number;
  height?: number;
}

export default function SheetMusic({ data, width = 450, height = 150 }: SheetMusicProps) {
  const containerId = `vex-${Math.random().toString(36).substr(2, 9)}`;

  setTimeout(() => {
    const container = document.getElementById(containerId);
    if (!(container instanceof HTMLDivElement)) {
      return;
    }

    container.innerHTML = '';

    try {
      const vf = new Factory({
        renderer: { elementId: containerId, width, height }
      });

      const score = vf.EasyScore();
      const system = vf.System();

      const requestedTimeSig = data.timeSignature || '4/4';
      const clef = data.clef || 'treble';

      let notesStr = '';
      let normalizedNotes: Array<{ keys: string[]; duration: string }> = [];
      if (data.notes && Array.isArray(data.notes)) {
        normalizedNotes = data.notes;
        notesStr = normalizedNotes.map(n => {
          const keys = n.keys.map(k => k.replace('/', ''));
          if (keys.length <= 1) {
            return `${keys[0]}/${n.duration}`;
          }
          return `(${keys.join(' ')})/${n.duration}`;
        }).join(', ');
      }

      if (!notesStr) notesStr = 'B4/w';
      if (normalizedNotes.length === 0) {
        normalizedNotes = [{ keys: ['b/4'], duration: 'w' }];
      }

      const timeSig = normalizeTimeSignatureForNotes(requestedTimeSig, normalizedNotes);

      const voice = score.voice(score.notes(notesStr, { stem: 'auto' }), { time: timeSig });
      voice.setMode(Voice.Mode.SOFT);

      const stave = system.addStave({
        voices: [voice]
      })
      .addClef(clef)
      .addTimeSignature(timeSig);

      if (data.keySignature) {
        stave.addKeySignature(data.keySignature);
      }

      vf.draw();
    } catch (e) {
      console.error('VexFlow Render Error:', e);
      container.innerHTML = `<div class="error">Error rendering music: ${(e as Error).message}</div>`;
    }
  }, 50);

  return (
    <div className="sheet-music-container p-4 bg-white rounded-lg shadow-sm my-2 overflow-x-auto">
      <div id={containerId} className="vexflow-canvas flex justify-center"></div>
      <div className="text-xs text-gray-400 text-center mt-1">Generated by Monsieur Engraver</div>
    </div>
  );
}
